package com.example.foodorder;

import com.example.foodorder.model.MenuItem;
import com.example.foodorder.model.Restaurant;
import com.example.foodorder.model.User;
import com.example.foodorder.repository.RestaurantRepository;
import com.example.foodorder.repository.UserRepository;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.security.crypto.password.PasswordEncoder;

import java.util.List;

@SpringBootApplication
public class FoodOrderApplication {

    public static void main(String[] args) {
        SpringApplication.run(FoodOrderApplication.class, args);
    }

    @Bean
    CommandLineRunner init(RestaurantRepository repo, UserRepository userRepository, PasswordEncoder passwordEncoder) {
        return args -> {
            // seed a default demo user if none exist
            userRepository.findByUsername("demo").orElseGet(() -> {
                User demo = new User();
                demo.setUsername("demo");
                demo.setEmail("demo@example.com");
                demo.setPassword(passwordEncoder.encode("demo123"));
                demo.setRoles(List.of("ROLE_USER"));
                return userRepository.save(demo);
            });

            // seed an admin user if missing
            userRepository.findByUsername("admin").orElseGet(() -> {
                User admin = new User();
                admin.setUsername("admin");
                admin.setEmail("admin@example.com");
                admin.setPassword(passwordEncoder.encode("admin123"));
                admin.setRoles(List.of("ROLE_ADMIN"));
                return userRepository.save(admin);
            });

            repo.deleteAll();
            
            // USA (9)
            Restaurant r1 = new Restaurant(null, "Sunset Diner", "American", "USA", "$", 4.5, "https://picsum.photos/seed/sunset/400/250", List.of(
                new MenuItem("Cheeseburger", "Beef patty with cheese", 8.99),
                new MenuItem("Fries", "Crispy fries", 3.50),
                new MenuItem("Caesar Salad", "Fresh romaine lettuce", 7.99),
                new MenuItem("Chicken Wings", "Buffalo style with ranch", 9.99),
                new MenuItem("Onion Rings", "Golden fried", 4.99),
                new MenuItem("Grilled Chicken Sandwich", "With lettuce and tomato", 10.99),
                new MenuItem("BLT Sandwich", "Bacon, lettuce, tomato", 8.99),
                new MenuItem("Milkshake", "Vanilla, chocolate, or strawberry", 5.99),
                new MenuItem("Pancakes", "Fluffy buttermilk stack", 7.99),
                new MenuItem("Bacon & Eggs", "Classic breakfast", 9.99),
                new MenuItem("Club Sandwich", "Triple decker", 11.99),
                new MenuItem("Chicken Tenders", "Crispy strips", 8.99),
                new MenuItem("Coleslaw", "Creamy cabbage slaw", 3.99),
                new MenuItem("Mozzarella Sticks", "Fried cheese sticks", 6.99),
                new MenuItem("Fish Sandwich", "Breaded cod", 9.99),
                new MenuItem("Garden Salad", "Mixed greens", 6.99),
                new MenuItem("Apple Pie", "Homemade with ice cream", 5.99),
                new MenuItem("Chocolate Cake", "Rich and moist", 6.99),
                new MenuItem("Coffee", "Fresh brewed", 2.99),
                new MenuItem("Iced Tea", "Sweet or unsweet", 2.99)
            ));
            Restaurant r2 = new Restaurant(null, "BBQ Nation", "Barbecue", "USA", "$", 4.5, "https://picsum.photos/seed/bbq/400/250", List.of(
                new MenuItem("Pulled Pork", "Slow-cooked with BBQ sauce", 15.99),
                new MenuItem("Ribs", "Fall-off-the-bone tender", 18.99),
                new MenuItem("Brisket", "Smoked beef brisket", 16.99),
                new MenuItem("BBQ Chicken", "Grilled with tangy sauce", 14.99),
                new MenuItem("Smoked Sausage", "House-made links", 12.99),
                new MenuItem("Mac & Cheese", "Creamy and cheesy", 6.99),
                new MenuItem("Coleslaw", "Tangy cabbage slaw", 4.99),
                new MenuItem("Cornbread", "Sweet and buttery", 3.99),
                new MenuItem("Baked Beans", "Slow-cooked with bacon", 5.99),
                new MenuItem("Potato Salad", "Classic American style", 5.99),
                new MenuItem("Collard Greens", "Southern style", 5.99),
                new MenuItem("Beef Burnt Ends", "Caramelized brisket", 17.99),
                new MenuItem("BBQ Combo Platter", "Mix of meats", 22.99),
                new MenuItem("Pulled Chicken", "Smoked and shredded", 13.99),
                new MenuItem("Grilled Corn", "Buttered corn on the cob", 4.99),
                new MenuItem("Jalapeno Poppers", "Cheese-stuffed peppers", 7.99),
                new MenuItem("Fried Pickles", "Crispy dill pickles", 6.99),
                new MenuItem("Peach Cobbler", "Warm with vanilla ice cream", 6.99),
                new MenuItem("Sweet Tea", "Southern classic", 2.99),
                new MenuItem("Lemonade", "Fresh-squeezed", 3.99)
            ));
            Restaurant r3 = new Restaurant(null, "The Green Bowl", "Vegan", "USA", "$", 4.4, "https://picsum.photos/seed/green/400/250", List.of(
                new MenuItem("Buddha Bowl", "Quinoa with roasted veggies", 12.99),
                new MenuItem("Vegan Burger", "Plant-based patty", 11.99),
                new MenuItem("Acai Bowl", "Superfood smoothie bowl", 9.99),
                new MenuItem("Tofu Scramble", "Seasoned tofu breakfast", 10.99),
                new MenuItem("Kale Salad", "Massaged kale with lemon", 11.99),
                new MenuItem("Veggie Wrap", "Hummus and fresh vegetables", 9.99),
                new MenuItem("Lentil Soup", "Hearty and nutritious", 7.99),
                new MenuItem("Quinoa Salad", "Mediterranean style", 10.99),
                new MenuItem("Avocado Toast", "Whole grain with toppings", 8.99),
                new MenuItem("Sweet Potato Fries", "Crispy and sweet", 5.99),
                new MenuItem("Falafel Plate", "Chickpea fritters", 11.99),
                new MenuItem("Vegan Pizza", "Dairy-free cheese", 13.99),
                new MenuItem("Green Smoothie", "Spinach, banana, mango", 6.99),
                new MenuItem("Veggie Tacos", "Black beans and corn", 10.99),
                new MenuItem("Mushroom Risotto", "Creamy and rich", 14.99),
                new MenuItem("Raw Energy Balls", "Date and nut bites", 5.99),
                new MenuItem("Cauliflower Wings", "Buffalo style", 9.99),
                new MenuItem("Chia Pudding", "Coconut milk based", 6.99),
                new MenuItem("Kombucha", "Fermented tea", 4.99),
                new MenuItem("Fresh Juice", "Carrot, apple, ginger", 5.99)
            ));
            Restaurant r4 = new Restaurant(null, "New York Steakhouse", "Steakhouse", "USA", "$", 4.8, "https://picsum.photos/seed/steak/400/250", List.of(
                new MenuItem("Ribeye Steak", "Prime aged beef", 32.99),
                new MenuItem("Lobster Tail", "Fresh Atlantic lobster", 28.99),
                new MenuItem("Filet Mignon", "Tender beef medallion", 36.99),
                new MenuItem("New York Strip", "Classic cut", 34.99),
                new MenuItem("Porterhouse", "T-bone for two", 45.99),
                new MenuItem("Surf & Turf", "Steak and lobster combo", 42.99),
                new MenuItem("Lamb Chops", "Grilled to perfection", 29.99),
                new MenuItem("Beef Wellington", "Puff pastry wrapped", 38.99),
                new MenuItem("Grilled Salmon", "Atlantic salmon fillet", 26.99),
                new MenuItem("Shrimp Scampi", "Garlic butter sauce", 24.99),
                new MenuItem("Caesar Salad", "Classic with anchovies", 10.99),
                new MenuItem("Wedge Salad", "Iceberg with blue cheese", 11.99),
                new MenuItem("Lobster Bisque", "Creamy soup", 12.99),
                new MenuItem("Baked Potato", "Loaded with toppings", 7.99),
                new MenuItem("Creamed Spinach", "Rich and creamy", 8.99),
                new MenuItem("Asparagus", "Grilled with hollandaise", 9.99),
                new MenuItem("Onion Rings", "Crispy beer-battered", 8.99),
                new MenuItem("Chocolate Lava Cake", "Molten center", 9.99),
                new MenuItem("Cheesecake", "New York style", 8.99),
                new MenuItem("Cabernet Sauvignon", "Glass of red wine", 12.99)
            ));
            Restaurant r5 = new Restaurant(null, "California Pizza", "Pizza", "USA", "$", 4.3, "https://picsum.photos/seed/calpizza/400/250", List.of(
                new MenuItem("BBQ Chicken Pizza", "Tangy BBQ sauce", 14.99),
                new MenuItem("Hawaiian Pizza", "Ham and pineapple", 13.99),
                new MenuItem("Margherita Pizza", "Fresh mozzarella and basil", 12.99),
                new MenuItem("Pepperoni Pizza", "Classic favorite", 13.99),
                new MenuItem("Veggie Supreme", "Loaded with vegetables", 14.99),
                new MenuItem("Meat Lovers", "Sausage, bacon, pepperoni", 15.99),
                new MenuItem("Four Cheese", "Mozzarella, parmesan, ricotta, feta", 14.99),
                new MenuItem("Buffalo Chicken", "Spicy chicken with ranch", 15.99),
                new MenuItem("Mediterranean", "Olives, feta, tomatoes", 14.99),
                new MenuItem("White Pizza", "Garlic, ricotta, mozzarella", 13.99),
                new MenuItem("Mushroom Truffle", "Gourmet mushrooms", 16.99),
                new MenuItem("Garlic Knots", "Buttery garlic bread", 5.99),
                new MenuItem("Mozzarella Sticks", "Fried cheese", 7.99),
                new MenuItem("Caesar Salad", "Crisp romaine", 8.99),
                new MenuItem("Greek Salad", "Feta and olives", 9.99),
                new MenuItem("Chicken Wings", "BBQ or buffalo", 10.99),
                new MenuItem("Calzone", "Folded pizza pocket", 12.99),
                new MenuItem("Breadsticks", "With marinara sauce", 4.99),
                new MenuItem("Tiramisu", "Italian dessert", 6.99),
                new MenuItem("Soda", "Coke, Sprite, or Fanta", 2.99)
            ));
            Restaurant r6 = new Restaurant(null, "Southern Comfort", "Southern", "USA", "$", 4.6, "https://picsum.photos/seed/southern/400/250", List.of(
                new MenuItem("Fried Chicken", "Crispy buttermilk chicken", 13.99),
                new MenuItem("Mac & Cheese", "Creamy comfort food", 7.99),
                new MenuItem("Chicken & Waffles", "Sweet and savory combo", 14.99),
                new MenuItem("Catfish", "Fried or blackened", 15.99),
                new MenuItem("Shrimp & Grits", "Southern classic", 16.99),
                new MenuItem("Country Fried Steak", "With gravy", 13.99),
                new MenuItem("Gumbo", "Louisiana seafood stew", 11.99),
                new MenuItem("Jambalaya", "Spicy rice dish", 12.99),
                new MenuItem("Cornbread", "Sweet and buttery", 3.99),
                new MenuItem("Collard Greens", "Slow-cooked with ham", 5.99),
                new MenuItem("Black-Eyed Peas", "With bacon", 5.99),
                new MenuItem("Hush Puppies", "Fried cornmeal balls", 4.99),
                new MenuItem("Okra", "Fried or stewed", 5.99),
                new MenuItem("Biscuits & Gravy", "Breakfast classic", 8.99),
                new MenuItem("Sweet Potato Casserole", "Marshmallow topped", 6.99),
                new MenuItem("Fried Green Tomatoes", "Crispy Southern appetizer", 7.99),
                new MenuItem("Red Beans & Rice", "New Orleans style", 9.99),
                new MenuItem("Pecan Pie", "Sweet and nutty", 6.99),
                new MenuItem("Banana Pudding", "Layered dessert", 5.99),
                new MenuItem("Sweet Tea", "Southern staple", 2.99)
            ));
            Restaurant r7 = new Restaurant(null, "Seafood Shack", "Seafood", "USA", "$", 4.7, "https://picsum.photos/seed/seafood/400/250", List.of(
                new MenuItem("Fish & Chips", "Beer-battered cod", 15.99),
                new MenuItem("Clam Chowder", "New England style", 8.99),
                new MenuItem("Lobster Roll", "Maine style on a bun", 22.99),
                new MenuItem("Crab Cakes", "Maryland style", 18.99),
                new MenuItem("Shrimp Basket", "Fried with cocktail sauce", 16.99),
                new MenuItem("Oysters", "Raw or fried", 14.99),
                new MenuItem("Grilled Salmon", "Lemon butter sauce", 19.99),
                new MenuItem("Fish Tacos", "Blackened with slaw", 13.99),
                new MenuItem("Calamari", "Fried squid rings", 11.99),
                new MenuItem("Mussels", "White wine garlic sauce", 15.99),
                new MenuItem("Scallops", "Pan-seared", 24.99),
                new MenuItem("Seafood Platter", "Mixed fried seafood", 26.99),
                new MenuItem("Tuna Steak", "Seared rare", 21.99),
                new MenuItem("Clam Strips", "Breaded and fried", 12.99),
                new MenuItem("Crab Legs", "Snow crab with butter", 29.99),
                new MenuItem("Shrimp Scampi", "Garlic butter pasta", 17.99),
                new MenuItem("Coleslaw", "Creamy cabbage", 3.99),
                new MenuItem("Hush Puppies", "Cornmeal fritters", 4.99),
                new MenuItem("Key Lime Pie", "Florida classic", 6.99),
                new MenuItem("Beer", "Local craft brew", 5.99)
            ));
            Restaurant r8 = new Restaurant(null, "Taco Fiesta", "Mexican", "USA", "$", 4.3, "https://picsum.photos/seed/taco/400/250", List.of(
                new MenuItem("Beef Tacos", "Seasoned beef", 9.99),
                new MenuItem("Quesadilla", "Cheese-filled tortilla", 8.99),
                new MenuItem("Chicken Tacos", "Grilled chicken", 9.99),
                new MenuItem("Fish Tacos", "Battered tilapia", 10.99),
                new MenuItem("Burrito Bowl", "Rice, beans, meat", 11.99),
                new MenuItem("Enchiladas", "Cheese or chicken", 12.99),
                new MenuItem("Nachos Supreme", "Loaded with toppings", 10.99),
                new MenuItem("Guacamole & Chips", "Fresh avocado dip", 6.99),
                new MenuItem("Salsa & Chips", "House-made salsa", 4.99),
                new MenuItem("Chile Relleno", "Stuffed pepper", 11.99),
                new MenuItem("Tamales", "Corn masa wrapped", 9.99),
                new MenuItem("Carnitas", "Slow-cooked pork", 12.99),
                new MenuItem("Carne Asada", "Grilled steak", 14.99),
                new MenuItem("Tostadas", "Crispy tortilla base", 8.99),
                new MenuItem("Mexican Rice", "Tomato-flavored rice", 3.99),
                new MenuItem("Refried Beans", "Creamy pinto beans", 3.99),
                new MenuItem("Churros", "Cinnamon sugar pastry", 5.99),
                new MenuItem("Flan", "Caramel custard", 5.99),
                new MenuItem("Margarita", "Frozen or on the rocks", 7.99),
                new MenuItem("Horchata", "Rice cinnamon drink", 3.99)
            ));
            Restaurant r9 = new Restaurant(null, "Texas Roadhouse", "American", "USA", "$", 4.5, "https://picsum.photos/seed/texas/400/250", List.of(
                new MenuItem("Chicken Fried Steak", "Country-style", 14.99),
                new MenuItem("Loaded Baked Potato", "Sour cream & bacon", 5.99),
                new MenuItem("Sirloin Steak", "8 oz grilled", 16.99),
                new MenuItem("Baby Back Ribs", "Full rack", 19.99),
                new MenuItem("Grilled Chicken", "Marinated breast", 13.99),
                new MenuItem("Pulled Pork Sandwich", "BBQ sauce", 11.99),
                new MenuItem("Fried Catfish", "Southern style", 14.99),
                new MenuItem("Meatloaf", "Homestyle with gravy", 12.99),
                new MenuItem("Pot Roast", "Slow-cooked beef", 15.99),
                new MenuItem("Chicken Tenders", "Hand-breaded", 11.99),
                new MenuItem("House Salad", "Mixed greens", 6.99),
                new MenuItem("Cactus Blossom", "Fried onion appetizer", 8.99),
                new MenuItem("Cheese Fries", "Loaded with cheese", 6.99),
                new MenuItem("Green Beans", "Seasoned side", 3.99),
                new MenuItem("Mashed Potatoes", "With gravy", 4.99),
                new MenuItem("Corn on the Cob", "Buttered", 3.99),
                new MenuItem("Rolls", "Fresh baked with butter", 2.99),
                new MenuItem("Brownie Sundae", "Warm with ice cream", 6.99),
                new MenuItem("Strawberry Cheesecake", "Classic dessert", 7.99),
                new MenuItem("Root Beer Float", "Ice cream and soda", 4.99)
            ));
            
            // India (9)
            Restaurant r10 = new Restaurant(null, "Spice Route", "Indian", "India", "Rs.", 4.7, "https://picsum.photos/seed/spice/400/250", List.of(
                new MenuItem("Butter Chicken", "Creamy tomato gravy", 450.00),
                new MenuItem("Naan", "Tandoori flatbread", 40.00),
                new MenuItem("Garlic Naan", "With fresh garlic", 60.00),
                new MenuItem("Paneer Butter Masala", "Cottage cheese in rich gravy", 380.00),
                new MenuItem("Chicken Tikka Masala", "Grilled chicken in spiced sauce", 420.00),
                new MenuItem("Dal Makhani", "Black lentils in cream", 320.00),
                new MenuItem("Biryani", "Aromatic rice with spices", 380.00),
                new MenuItem("Tandoori Chicken", "Half piece marinated", 450.00),
                new MenuItem("Palak Paneer", "Spinach with cottage cheese", 360.00),
                new MenuItem("Rogan Josh", "Lamb curry", 520.00),
                new MenuItem("Aloo Gobi", "Potato and cauliflower", 280.00),
                new MenuItem("Chicken Korma", "Mild creamy curry", 400.00),
                new MenuItem("Mixed Vegetable Curry", "Seasonal vegetables", 300.00),
                new MenuItem("Raita", "Yogurt with cucumber", 80.00),
                new MenuItem("Papad", "Crispy lentil wafer", 30.00),
                new MenuItem("Jeera Rice", "Cumin flavored rice", 180.00),
                new MenuItem("Mango Lassi", "Sweet yogurt drink", 120.00),
                new MenuItem("Gulab Jamun", "Sweet milk dumplings", 100.00),
                new MenuItem("Kulfi", "Indian ice cream", 90.00),
                new MenuItem("Masala Chai", "Spiced tea", 40.00)
            ));
            Restaurant r11 = new Restaurant(null, "Tandoor Express", "Indian", "India", "Rs.", 4.6, "https://picsum.photos/seed/tandoor/400/250", List.of(
                new MenuItem("Chicken Tikka", "Grilled marinated chicken", 380.00),
                new MenuItem("Dal Makhani", "Black lentils in cream", 320.00),
                new MenuItem("Tandoori Roti", "Whole wheat flatbread", 30.00),
                new MenuItem("Paneer Tikka", "Grilled cottage cheese", 360.00),
                new MenuItem("Seekh Kebab", "Minced meat skewers", 420.00),
                new MenuItem("Tandoori Prawns", "Grilled jumbo prawns", 680.00),
                new MenuItem("Chicken Malai Tikka", "Creamy marinated chicken", 400.00),
                new MenuItem("Mutton Seekh Kebab", "Lamb skewers", 480.00),
                new MenuItem("Paneer Butter Masala", "Rich cottage cheese curry", 380.00),
                new MenuItem("Kadhai Chicken", "Spicy wok-cooked chicken", 420.00),
                new MenuItem("Dal Tadka", "Tempered yellow lentils", 280.00),
                new MenuItem("Mushroom Masala", "Button mushrooms in gravy", 340.00),
                new MenuItem("Butter Naan", "Buttered flatbread", 50.00),
                new MenuItem("Laccha Paratha", "Layered flatbread", 60.00),
                new MenuItem("Green Salad", "Fresh vegetables", 100.00),
                new MenuItem("Onion Salad", "Sliced onions with lemon", 60.00),
                new MenuItem("Mint Chutney", "Fresh mint sauce", 40.00),
                new MenuItem("Sweet Lassi", "Sweet yogurt drink", 100.00),
                new MenuItem("Rasmalai", "Cottage cheese in sweet milk", 120.00),
                new MenuItem("Nimbu Pani", "Fresh lemonade", 60.00)
            ));
            Restaurant r12 = new Restaurant(null, "Mumbai Masala", "Indian", "India", "Rs.", 4.5, "https://picsum.photos/seed/mumbai/400/250", List.of(
                new MenuItem("Paneer Tikka", "Cottage cheese kebab", 360.00),
                new MenuItem("Samosa", "Crispy potato pastry", 40.00),
                new MenuItem("Pav Bhaji", "Mashed vegetables with bread", 180.00),
                new MenuItem("Vada Pav", "Mumbai burger", 60.00),
                new MenuItem("Misal Pav", "Spicy sprouts curry", 140.00),
                new MenuItem("Pani Puri", "Crispy water balls", 80.00),
                new MenuItem("Bhel Puri", "Puffed rice chaat", 100.00),
                new MenuItem("Sev Puri", "Crispy canapes", 100.00),
                new MenuItem("Dahi Puri", "Yogurt filled puri", 100.00),
                new MenuItem("Ragda Pattice", "Potato patties with curry", 120.00),
                new MenuItem("Chicken Biryani", "Mumbai style", 380.00),
                new MenuItem("Mutton Biryani", "Aromatic lamb rice", 480.00),
                new MenuItem("Butter Chicken", "Creamy tomato curry", 420.00),
                new MenuItem("Chole Bhature", "Chickpea curry with fried bread", 200.00),
                new MenuItem("Aloo Paratha", "Potato stuffed flatbread", 80.00),
                new MenuItem("Paneer Paratha", "Cottage cheese stuffed", 100.00),
                new MenuItem("Masala Dosa", "Crispy rice crepe", 140.00),
                new MenuItem("Falooda", "Rose milk dessert", 140.00),
                new MenuItem("Jalebi", "Sweet crispy spirals", 80.00),
                new MenuItem("Cutting Chai", "Mumbai style tea", 30.00)
            ));
            Restaurant r13 = new Restaurant(null, "Delhi Darbar", "Indian", "India", "Rs.", 4.8, "https://picsum.photos/seed/delhi/400/250", List.of(
                new MenuItem("Rogan Josh", "Kashmiri lamb curry", 550.00),
                new MenuItem("Palak Paneer", "Spinach & cottage cheese", 380.00),
                new MenuItem("Butter Naan", "Buttered tandoori bread", 50.00),
                new MenuItem("Tandoori Chicken", "Full piece", 680.00),
                new MenuItem("Dal Bukhara", "Black lentils slow cooked", 350.00),
                new MenuItem("Nihari", "Slow-cooked meat stew", 520.00),
                new MenuItem("Korma", "Mild creamy curry", 480.00),
                new MenuItem("Kebab Platter", "Assorted grilled meats", 750.00),
                new MenuItem("Chicken Changezi", "Delhi specialty curry", 460.00),
                new MenuItem("Mutton Rara", "Minced and cubed lamb", 580.00),
                new MenuItem("Shahi Paneer", "Royal cottage cheese curry", 400.00),
                new MenuItem("Malai Kofta", "Vegetable dumplings in cream", 380.00),
                new MenuItem("Stuffed Kulcha", "Filled flatbread", 80.00),
                new MenuItem("Roomali Roti", "Thin handkerchief bread", 40.00),
                new MenuItem("Kashmiri Pulao", "Sweet rice with fruits", 280.00),
                new MenuItem("Chicken Tikka Roll", "Wrap with grilled chicken", 180.00),
                new MenuItem("Papdi Chaat", "Crispy chaat", 120.00),
                new MenuItem("Shahi Tukda", "Bread pudding dessert", 140.00),
                new MenuItem("Rabri", "Condensed milk dessert", 120.00),
                new MenuItem("Thandai", "Spiced milk drink", 100.00)
            ));
            Restaurant r14 = new Restaurant(null, "Curry House", "Indian", "India", "Rs.", 4.4, "https://picsum.photos/seed/curry/400/250", List.of(
                new MenuItem("Chicken Vindaloo", "Spicy Goan curry", 420.00),
                new MenuItem("Aloo Gobi", "Potato & cauliflower", 300.00),
                new MenuItem("Chicken Madras", "South Indian spicy curry", 400.00),
                new MenuItem("Prawn Curry", "Coastal style prawns", 580.00),
                new MenuItem("Fish Curry", "Kerala style", 480.00),
                new MenuItem("Egg Curry", "Boiled eggs in masala", 280.00),
                new MenuItem("Goan Fish Curry", "Coconut based", 520.00),
                new MenuItem("Chicken Chettinad", "Tamil Nadu specialty", 440.00),
                new MenuItem("Mutton Curry", "Traditional recipe", 520.00),
                new MenuItem("Vegetable Jalfrezi", "Stir-fried veggies", 320.00),
                new MenuItem("Bhindi Masala", "Okra curry", 280.00),
                new MenuItem("Baingan Bharta", "Smoked eggplant", 300.00),
                new MenuItem("Rajma", "Red kidney beans curry", 260.00),
                new MenuItem("Steamed Rice", "Plain basmati", 120.00),
                new MenuItem("Lemon Rice", "Tangy south Indian rice", 160.00),
                new MenuItem("Appam", "Rice pancake", 80.00),
                new MenuItem("Pickle", "Mixed Indian pickle", 40.00),
                new MenuItem("Coconut Chutney", "Fresh coconut dip", 50.00),
                new MenuItem("Payasam", "Sweet rice pudding", 100.00),
                new MenuItem("Filter Coffee", "South Indian style", 60.00)
            ));
            Restaurant r15 = new Restaurant(null, "Biryani Palace", "Indian", "India", "Rs.", 4.7, "https://picsum.photos/seed/biryani/400/250", List.of(
                new MenuItem("Hyderabadi Biryani", "Spiced rice & meat", 420.00),
                new MenuItem("Chicken Biryani", "Aromatic chicken rice", 380.00),
                new MenuItem("Mutton Biryani", "Lamb with basmati", 480.00),
                new MenuItem("Vegetable Biryani", "Mixed veggie rice", 300.00),
                new MenuItem("Egg Biryani", "Boiled eggs in rice", 260.00),
                new MenuItem("Prawn Biryani", "Seafood specialty", 520.00),
                new MenuItem("Lucknowi Biryani", "Awadhi style", 450.00),
                new MenuItem("Kolkata Biryani", "With potato", 380.00),
                new MenuItem("Raita", "Yogurt side", 80.00),
                new MenuItem("Mirchi Ka Salan", "Pepper curry side", 120.00),
                new MenuItem("Bagara Baingan", "Eggplant curry", 280.00),
                new MenuItem("Double Ka Meetha", "Bread pudding", 120.00),
                new MenuItem("Gulab Jamun", "Sweet milk dumplings", 100.00),
                new MenuItem("Shorba", "Clear soup", 140.00),
                new MenuItem("Chicken 65", "Spicy fried chicken", 320.00),
                new MenuItem("Paneer 65", "Fried cottage cheese", 280.00),
                new MenuItem("Tandoori Chicken", "Half piece", 380.00),
                new MenuItem("Naan", "Plain flatbread", 40.00),
                new MenuItem("Kheer", "Rice pudding", 100.00),
                new MenuItem("Buttermilk", "Spiced chaas", 60.00)
            ));
            Restaurant r16 = new Restaurant(null, "Masala Magic", "Indian", "India", "Rs.", 4.6, "https://picsum.photos/seed/masala/400/250", List.of(
                new MenuItem("Chole Bhature", "Chickpea curry & bread", 180.00),
                new MenuItem("Pani Puri", "Crispy water balls", 80.00),
                new MenuItem("Aloo Tikki", "Potato patties", 100.00),
                new MenuItem("Papdi Chaat", "Crispy wafers with toppings", 120.00),
                new MenuItem("Dahi Bhalla", "Lentil dumplings in yogurt", 120.00),
                new MenuItem("Raj Kachori", "Large stuffed kachori", 140.00),
                new MenuItem("Samosa Chaat", "Samosa with chickpeas", 120.00),
                new MenuItem("Pav Bhaji", "Vegetable curry with bread", 180.00),
                new MenuItem("Paneer Tikka", "Grilled cottage cheese", 340.00),
                new MenuItem("Malai Chaap", "Creamy soy chaap", 300.00),
                new MenuItem("Chilli Paneer", "Indo-Chinese style", 320.00),
                new MenuItem("Gobi Manchurian", "Cauliflower fritters", 280.00),
                new MenuItem("Veg Hakka Noodles", "Stir-fried noodles", 200.00),
                new MenuItem("Veg Fried Rice", "Indo-Chinese rice", 180.00),
                new MenuItem("Spring Rolls", "Crispy vegetable rolls", 180.00),
                new MenuItem("Masala Dosa", "South Indian crepe", 140.00),
                new MenuItem("Uttapam", "Thick rice pancake", 160.00),
                new MenuItem("Vada", "Lentil fritters", 80.00),
                new MenuItem("Kulfi Falooda", "Ice cream dessert", 140.00),
                new MenuItem("Masala Soda", "Spiced lemonade", 60.00)
            ));
            Restaurant r17 = new Restaurant(null, "South Indian Kitchen", "Indian", "India", "Rs.", 4.5, "https://picsum.photos/seed/southind/400/250", List.of(
                new MenuItem("Dosa", "Crispy rice crepe", 100.00),
                new MenuItem("Idli Sambar", "Steamed rice cakes", 80.00),
                new MenuItem("Masala Dosa", "Potato filled dosa", 120.00),
                new MenuItem("Rava Dosa", "Semolina crepe", 130.00),
                new MenuItem("Onion Uttapam", "Thick pancake with onions", 140.00),
                new MenuItem("Medu Vada", "Lentil donuts", 80.00),
                new MenuItem("Pongal", "Rice and lentil porridge", 100.00),
                new MenuItem("Upma", "Semolina breakfast", 90.00),
                new MenuItem("Coconut Chutney", "Fresh coconut dip", 30.00),
                new MenuItem("Tomato Chutney", "Spicy tomato dip", 30.00),
                new MenuItem("Sambar", "Lentil vegetable stew", 60.00),
                new MenuItem("Rasam", "Tangy tamarind soup", 50.00),
                new MenuItem("Curd Rice", "Yogurt rice", 100.00),
                new MenuItem("Lemon Rice", "Tangy rice", 120.00),
                new MenuItem("Tamarind Rice", "Sour rice", 120.00),
                new MenuItem("Bisi Bele Bath", "Mixed rice dish", 140.00),
                new MenuItem("Mysore Pak", "Sweet gram flour fudge", 100.00),
                new MenuItem("Payasam", "Sweet milk dessert", 80.00),
                new MenuItem("Filter Coffee", "South Indian coffee", 50.00),
                new MenuItem("Buttermilk", "Spiced yogurt drink", 40.00)
            ));
            Restaurant r18 = new Restaurant(null, "Royal Rajasthan", "Indian", "India", "Rs.", 4.7, "https://picsum.photos/seed/rajasthan/400/250", List.of(
                new MenuItem("Dal Baati", "Lentils with bread balls", 320.00),
                new MenuItem("Laal Maas", "Spicy red meat curry", 580.00),
                new MenuItem("Gatte Ki Sabzi", "Gram flour dumplings", 280.00),
                new MenuItem("Ker Sangri", "Desert bean vegetable", 300.00),
                new MenuItem("Papad Ki Sabzi", "Papad in yogurt curry", 220.00),
                new MenuItem("Mirchi Vada", "Stuffed chili fritters", 120.00),
                new MenuItem("Pyaaz Kachori", "Onion filled pastry", 60.00),
                new MenuItem("Mawa Kachori", "Sweet milk kachori", 80.00),
                new MenuItem("Dal Bati Churma", "Complete traditional meal", 380.00),
                new MenuItem("Safed Maas", "White mutton curry", 550.00),
                new MenuItem("Jungli Maas", "Wild game style curry", 600.00),
                new MenuItem("Bajre Ki Roti", "Millet flatbread", 40.00),
                new MenuItem("Makki Ki Roti", "Corn flatbread", 40.00),
                new MenuItem("Missi Roti", "Spiced gram flour bread", 50.00),
                new MenuItem("Panchmel Dal", "Five lentil mix", 280.00),
                new MenuItem("Rajasthani Kadhi", "Yogurt curry with pakoda", 260.00),
                new MenuItem("Churma", "Sweet wheat balls", 140.00),
                new MenuItem("Ghevar", "Honeycomb dessert", 180.00),
                new MenuItem("Malpua", "Sweet fried pancakes", 120.00),
                new MenuItem("Kesar Lassi", "Saffron yogurt drink", 120.00)
            ));
            
            // Japan (9)
            Restaurant r19 = new Restaurant(null, "Tokyo Express", "Japanese", "Japan", "¥", 4.8, "https://picsum.photos/seed/tokyo/400/250", List.of(
                new MenuItem("Sushi Platter", "Assorted fresh sushi", 2800.00),
                new MenuItem("Ramen", "Rich pork bone broth", 1200.00),
                new MenuItem("Tempura", "Crispy battered seafood", 1500.00),
                new MenuItem("Sashimi", "Fresh raw fish slices", 2500.00),
                new MenuItem("Tonkatsu", "Breaded pork cutlet", 1300.00),
                new MenuItem("Gyoza", "Pan-fried dumplings", 800.00),
                new MenuItem("Yakitori", "Grilled chicken skewers", 1000.00),
                new MenuItem("Udon", "Thick wheat noodles", 1100.00),
                new MenuItem("Teriyaki Chicken", "Sweet glazed chicken", 1400.00),
                new MenuItem("Miso Soup", "Fermented soybean soup", 500.00),
                new MenuItem("Edamame", "Steamed soybeans", 600.00),
                new MenuItem("California Roll", "Crab and avocado", 1200.00),
                new MenuItem("Salmon Nigiri", "Fresh salmon on rice", 1500.00),
                new MenuItem("Tuna Nigiri", "Fresh tuna on rice", 1600.00),
                new MenuItem("Eel Roll", "Grilled eel sushi", 1800.00),
                new MenuItem("Chicken Katsu Curry", "Breaded chicken with curry", 1400.00),
                new MenuItem("Takoyaki", "Octopus balls", 900.00),
                new MenuItem("Green Tea Ice Cream", "Matcha dessert", 700.00),
                new MenuItem("Mochi", "Sweet rice cake", 600.00),
                new MenuItem("Sake", "Japanese rice wine", 1000.00)
            ));
            Restaurant r20 = new Restaurant(null, "Osaka Delights", "Japanese", "Japan", "¥", 4.7, "https://picsum.photos/seed/osaka/400/250", List.of(
                new MenuItem("Takoyaki", "Octopus balls", 900.00),
                new MenuItem("Okonomiyaki", "Savory pancake", 1200.00),
                new MenuItem("Kushikatsu", "Deep-fried skewers", 1400.00),
                new MenuItem("Yakisoba", "Fried noodles", 1000.00),
                new MenuItem("Negiyaki", "Green onion pancake", 1100.00),
                new MenuItem("Doteyaki", "Beef tendon stew", 1300.00),
                new MenuItem("Kitsune Udon", "Udon with fried tofu", 1000.00),
                new MenuItem("Osaka Sushi", "Box-pressed sushi", 2000.00),
                new MenuItem("Ikayaki", "Grilled squid", 1100.00),
                new MenuItem("Taiyaki", "Fish-shaped cake", 500.00),
                new MenuItem("Kushi Dango", "Rice dumpling skewers", 600.00),
                new MenuItem("Gyoza", "Pan-fried dumplings", 800.00),
                new MenuItem("Ebi Fry", "Fried shrimp", 1500.00),
                new MenuItem("Tonkatsu", "Pork cutlet", 1400.00),
                new MenuItem("Miso Katsu", "Pork with miso sauce", 1500.00),
                new MenuItem("Hitsumabushi", "Grilled eel on rice", 2800.00),
                new MenuItem("Kakiage", "Mixed vegetable tempura", 900.00),
                new MenuItem("Warabi Mochi", "Bracken starch cake", 700.00),
                new MenuItem("Matcha Parfait", "Green tea dessert", 900.00),
                new MenuItem("Ramune", "Japanese soda", 400.00)
            ));
            Restaurant r21 = new Restaurant(null, "Sushi Master", "Japanese", "Japan", "¥", 4.9, "https://picsum.photos/seed/sushim/400/250", List.of(
                new MenuItem("Omakase", "Chef's selection", 8500.00),
                new MenuItem("Sashimi", "Fresh raw fish", 3500.00),
                new MenuItem("Toro Nigiri", "Fatty tuna belly", 3000.00),
                new MenuItem("Uni Nigiri", "Sea urchin", 2500.00),
                new MenuItem("Otoro", "Premium fatty tuna", 3500.00),
                new MenuItem("Chu-toro", "Medium fatty tuna", 2800.00),
                new MenuItem("Ikura", "Salmon roe", 2000.00),
                new MenuItem("Hamachi", "Yellowtail", 1800.00),
                new MenuItem("Amaebi", "Sweet shrimp", 2000.00),
                new MenuItem("Hotate", "Scallop", 2200.00),
                new MenuItem("Unagi", "Grilled eel", 2500.00),
                new MenuItem("Tako", "Octopus", 1500.00),
                new MenuItem("Sake Nigiri", "Salmon", 1600.00),
                new MenuItem("Ebi", "Cooked shrimp", 1400.00),
                new MenuItem("Tamago", "Sweet egg omelet", 800.00),
                new MenuItem("Specialty Roll", "Chef's creation", 2800.00),
                new MenuItem("Miso Soup", "Traditional soup", 500.00),
                new MenuItem("Edamame", "Salted soybeans", 600.00),
                new MenuItem("Seaweed Salad", "Wakame salad", 800.00),
                new MenuItem("Premium Sake", "Junmai Daiginjo", 2500.00)
            ));
            Restaurant r22 = new Restaurant(null, "Ramen Yokocho", "Japanese", "Japan", "¥", 4.6, "https://picsum.photos/seed/ramen/400/250", List.of(
                new MenuItem("Tonkotsu Ramen", "Pork broth noodles", 1300.00),
                new MenuItem("Shoyu Ramen", "Soy sauce broth", 1200.00),
                new MenuItem("Miso Ramen", "Fermented soybean broth", 1250.00),
                new MenuItem("Shio Ramen", "Salt-based broth", 1200.00),
                new MenuItem("Spicy Ramen", "With chili oil", 1350.00),
                new MenuItem("Tsukemen", "Dipping ramen", 1400.00),
                new MenuItem("Chashu Ramen", "Extra pork belly", 1600.00),
                new MenuItem("Gyoza", "Pan-fried dumplings", 700.00),
                new MenuItem("Karaage", "Japanese fried chicken", 900.00),
                new MenuItem("Negi Ramen", "Green onion topped", 1350.00),
                new MenuItem("Corn Butter Ramen", "Hokkaido style", 1400.00),
                new MenuItem("Seafood Ramen", "Mixed seafood", 1500.00),
                new MenuItem("Vegetable Ramen", "Veggie broth", 1100.00),
                new MenuItem("Egg Drop Ramen", "Soft boiled egg", 1300.00),
                new MenuItem("Wonton Soup", "Dumpling soup", 1000.00),
                new MenuItem("Kimchi Ramen", "Korean spicy", 1350.00),
                new MenuItem("Takana", "Pickled mustard greens", 300.00),
                new MenuItem("Extra Chashu", "Pork belly slices", 500.00),
                new MenuItem("Ajitsuke Tamago", "Marinated egg", 200.00),
                new MenuItem("Iced Green Tea", "Cold matcha", 400.00)
            ));
            Restaurant r23 = new Restaurant(null, "Kyoto Garden", "Japanese", "Japan", "¥", 4.8, "https://picsum.photos/seed/kyoto/400/250", List.of(
                new MenuItem("Kaiseki", "Multi-course meal", 7500.00),
                new MenuItem("Matcha Ice Cream", "Green tea dessert", 800.00),
                new MenuItem("Yudofu", "Hot tofu pot", 1800.00),
                new MenuItem("Kyo-Kaiseki", "Kyoto style course", 8500.00),
                new MenuItem("Obanzai", "Traditional side dishes", 2000.00),
                new MenuItem("Tofu Dengaku", "Miso glazed tofu", 1200.00),
                new MenuItem("Yuba", "Tofu skin", 1500.00),
                new MenuItem("Shojin Ryori", "Buddhist vegetarian", 3500.00),
                new MenuItem("Kamonanban", "Duck noodles", 1800.00),
                new MenuItem("Nishin Soba", "Herring buckwheat noodles", 1600.00),
                new MenuItem("Grilled Ayu", "Sweetfish", 2200.00),
                new MenuItem("Kyoto Pickles", "Tsukemono assortment", 800.00),
                new MenuItem("Hamo", "Pike conger", 3000.00),
                new MenuItem("Tai Meshi", "Sea bream rice", 2500.00),
                new MenuItem("Goma Dofu", "Sesame tofu", 1000.00),
                new MenuItem("Warabi Mochi", "Bracken starch cake", 900.00),
                new MenuItem("Matcha Parfait", "Green tea layered dessert", 1200.00),
                new MenuItem("Nama Yatsuhashi", "Raw cinnamon mochi", 700.00),
                new MenuItem("Matcha Latte", "Green tea latte", 700.00),
                new MenuItem("Uji Tea", "Premium green tea", 600.00)
            ));
            Restaurant r24 = new Restaurant(null, "Tempura House", "Japanese", "Japan", "¥", 4.5, "https://picsum.photos/seed/tempura/400/250", List.of(
                new MenuItem("Shrimp Tempura", "Crispy fried shrimp", 2200.00),
                new MenuItem("Vegetable Tempura", "Mixed veggies", 1500.00),
                new MenuItem("Tempura Assortment", "Seafood and vegetables", 2800.00),
                new MenuItem("Kakiage", "Mixed vegetable fritter", 1200.00),
                new MenuItem("Sweet Potato Tempura", "Crispy sweet potato", 800.00),
                new MenuItem("Lotus Root Tempura", "Crispy renkon", 900.00),
                new MenuItem("Eggplant Tempura", "Fried nasu", 850.00),
                new MenuItem("Squid Tempura", "Crispy ika", 1600.00),
                new MenuItem("Fish Tempura", "White fish", 1800.00),
                new MenuItem("Scallop Tempura", "Fried hotate", 2000.00),
                new MenuItem("Mushroom Tempura", "Shiitake and enoki", 1000.00),
                new MenuItem("Tempura Don", "Tempura rice bowl", 1800.00),
                new MenuItem("Tendon", "Classic tempura bowl", 1600.00),
                new MenuItem("Tempura Udon", "Noodles with tempura", 1700.00),
                new MenuItem("Tempura Soba", "Buckwheat with tempura", 1700.00),
                new MenuItem("Tentsuyu", "Dipping sauce", 200.00),
                new MenuItem("Daikon Oroshi", "Grated radish", 300.00),
                new MenuItem("Green Tea", "Hot ocha", 400.00),
                new MenuItem("Miso Soup", "Soybean soup", 500.00),
                new MenuItem("Rice", "Steamed white rice", 400.00)
            ));
            Restaurant r25 = new Restaurant(null, "Izakaya Nights", "Japanese", "Japan", "¥", 4.7, "https://picsum.photos/seed/izakaya/400/250", List.of(
                new MenuItem("Yakitori", "Grilled chicken skewers", 1000.00),
                new MenuItem("Karaage", "Japanese fried chicken", 900.00),
                new MenuItem("Edamame", "Salted soybeans", 500.00),
                new MenuItem("Gyoza", "Pan-fried dumplings", 700.00),
                new MenuItem("Agedashi Tofu", "Fried tofu in broth", 800.00),
                new MenuItem("Takoyaki", "Octopus balls", 850.00),
                new MenuItem("Tori Nanban", "Chicken with tartar sauce", 1100.00),
                new MenuItem("Potato Salad", "Japanese style", 600.00),
                new MenuItem("Chawanmushi", "Savory egg custard", 700.00),
                new MenuItem("Grilled Squid", "Whole ika", 1300.00),
                new MenuItem("Negima", "Chicken and leek skewers", 950.00),
                new MenuItem("Tsukune", "Chicken meatball skewers", 900.00),
                new MenuItem("Shishito Peppers", "Blistered peppers", 650.00),
                new MenuItem("Shioyaki", "Salt-grilled fish", 1400.00),
                new MenuItem("Eihire", "Dried stingray fin", 800.00),
                new MenuItem("Nasu Dengaku", "Miso glazed eggplant", 850.00),
                new MenuItem("Cucumber Pickles", "Tsukemono", 400.00),
                new MenuItem("Onigiri", "Rice balls", 500.00),
                new MenuItem("Beer", "Draft Asahi", 700.00),
                new MenuItem("Sake", "Hot or cold", 900.00)
            ));
            Restaurant r26 = new Restaurant(null, "Udon Station", "Japanese", "Japan", "¥", 4.4, "https://picsum.photos/seed/udon/400/250", List.of(
                new MenuItem("Kitsune Udon", "Thick noodles with tofu", 1100.00),
                new MenuItem("Tempura Udon", "Noodles with tempura", 1400.00),
                new MenuItem("Kake Udon", "Plain udon soup", 900.00),
                new MenuItem("Zaru Udon", "Cold dipping noodles", 1000.00),
                new MenuItem("Niku Udon", "Beef udon", 1300.00),
                new MenuItem("Curry Udon", "Curry soup noodles", 1200.00),
                new MenuItem("Nabeyaki Udon", "Hot pot udon", 1500.00),
                new MenuItem("Tsukimi Udon", "Moon viewing udon with egg", 1100.00),
                new MenuItem("Tanuki Udon", "With tempura bits", 1000.00),
                new MenuItem("Wakame Udon", "Seaweed udon", 1050.00),
                new MenuItem("Yaki Udon", "Stir-fried udon", 1200.00),
                new MenuItem("Kamatama Udon", "Raw egg udon", 950.00),
                new MenuItem("Chikara Udon", "With mochi", 1150.00),
                new MenuItem("Kamo Nanban", "Duck udon", 1600.00),
                new MenuItem("Inari Sushi", "Tofu pouch sushi", 700.00),
                new MenuItem("Onigiri", "Rice balls", 450.00),
                new MenuItem("Kakiage", "Vegetable tempura", 800.00),
                new MenuItem("Chikuwa Tempura", "Fish cake tempura", 600.00),
                new MenuItem("Iced Green Tea", "Cold ocha", 350.00),
                new MenuItem("Hot Tea", "Green tea", 300.00)
            ));
            Restaurant r27 = new Restaurant(null, "Hokkaido Kitchen", "Japanese", "Japan", "¥", 4.6, "https://picsum.photos/seed/hokkaido/400/250", List.of(
                new MenuItem("Crab Hot Pot", "Fresh seafood stew", 4500.00),
                new MenuItem("Salmon Sashimi", "Hokkaido salmon", 2500.00),
                new MenuItem("Uni Don", "Sea urchin rice bowl", 3500.00),
                new MenuItem("Ikura Don", "Salmon roe bowl", 2800.00),
                new MenuItem("Hokkaido Ramen", "Miso butter corn", 1400.00),
                new MenuItem("Grilled King Crab", "Taraba-gani", 5500.00),
                new MenuItem("Jingisukan", "Grilled lamb", 2200.00),
                new MenuItem("Scallop Sashimi", "Fresh hotate", 2400.00),
                new MenuItem("Ishikari Nabe", "Salmon hot pot", 2800.00),
                new MenuItem("Zangi", "Hokkaido fried chicken", 1100.00),
                new MenuItem("Kaisendon", "Seafood rice bowl", 2600.00),
                new MenuItem("Atka Mackerel", "Grilled hokke", 1800.00),
                new MenuItem("Corn Butter", "Sweet corn side", 700.00),
                new MenuItem("Potato Croquette", "Hokkaido potato", 800.00),
                new MenuItem("Melon", "Yubari king melon", 3000.00),
                new MenuItem("Seafood Pizza", "Hokkaido style", 2000.00),
                new MenuItem("Squid Somen", "Thinly sliced squid", 1500.00),
                new MenuItem("Soft Serve Ice Cream", "Hokkaido milk", 600.00),
                new MenuItem("Cheese Tart", "Baked cheese dessert", 800.00),
                new MenuItem("Sapporo Beer", "Local draft", 800.00)
            ));
            
            // Italy (9)
            Restaurant r28 = new Restaurant(null, "La Bella Italia", "Italian", "Italy", "€", 4.6, "https://picsum.photos/seed/italia/400/250", List.of(
                new MenuItem("Margherita Pizza", "Classic tomato & mozzarella", 10.50),
                new MenuItem("Carbonara", "Creamy pasta with bacon", 12.50),
                new MenuItem("Lasagna", "Layered pasta with meat sauce", 13.50),
                new MenuItem("Spaghetti Bolognese", "Meat sauce pasta", 11.50),
                new MenuItem("Penne Arrabbiata", "Spicy tomato pasta", 10.00),
                new MenuItem("Risotto ai Funghi", "Mushroom risotto", 14.00),
                new MenuItem("Osso Buco", "Braised veal shanks", 22.00),
                new MenuItem("Saltimbocca", "Veal with prosciutto", 18.00),
                new MenuItem("Caprese Salad", "Tomato, mozzarella, basil", 9.50),
                new MenuItem("Bruschetta", "Tomato on toasted bread", 7.50),
                new MenuItem("Minestrone", "Vegetable soup", 8.00),
                new MenuItem("Calzone", "Folded pizza", 11.50),
                new MenuItem("Prosciutto e Melone", "Ham and melon", 10.50),
                new MenuItem("Arancini", "Fried rice balls", 8.50),
                new MenuItem("Panna Cotta", "Cooked cream dessert", 6.50),
                new MenuItem("Tiramisu", "Coffee dessert", 7.50),
                new MenuItem("Gelato", "Italian ice cream", 5.50),
                new MenuItem("Espresso", "Italian coffee", 2.50),
                new MenuItem("Cappuccino", "Coffee with milk", 3.50),
                new MenuItem("House Wine", "Red or white", 6.00)
            ));
            Restaurant r29 = new Restaurant(null, "Roma Trattoria", "Italian", "Italy", "€", 4.7, "https://picsum.photos/seed/roma/400/250", List.of(
                new MenuItem("Cacio e Pepe", "Cheese & pepper pasta", 11.50),
                new MenuItem("Amatriciana", "Tomato & guanciale", 12.50),
                new MenuItem("Carbonara Romana", "Traditional Roman style", 13.00),
                new MenuItem("Gricia", "Guanciale and pecorino", 12.00),
                new MenuItem("Saltimbocca alla Romana", "Veal Roman style", 19.00),
                new MenuItem("Coda alla Vaccinara", "Oxtail stew", 18.50),
                new MenuItem("Carciofi alla Giudia", "Jewish style artichokes", 11.00),
                new MenuItem("Supplì", "Fried rice croquettes", 7.50),
                new MenuItem("Fiori di Zucca", "Stuffed zucchini flowers", 9.50),
                new MenuItem("Bruschetta Romana", "Tomato bruschetta", 7.00),
                new MenuItem("Puntarelle", "Chicory salad", 8.50),
                new MenuItem("Pasta e Ceci", "Pasta with chickpeas", 10.50),
                new MenuItem("Abbacchio", "Roman lamb", 21.00),
                new MenuItem("Porchetta", "Roasted pork", 14.50),
                new MenuItem("Focaccia", "Italian flatbread", 4.50),
                new MenuItem("Maritozzo", "Sweet cream bun", 5.50),
                new MenuItem("Crostata", "Fruit tart", 6.50),
                new MenuItem("Grattachecca", "Shaved ice", 4.00),
                new MenuItem("Espresso Romano", "Coffee with lemon", 2.50),
                new MenuItem("Frascati Wine", "Local white wine", 7.00)
            ));
            Restaurant r30 = new Restaurant(null, "Venice Bistro", "Italian", "Italy", "€", 4.5, "https://picsum.photos/seed/venice/400/250", List.of(
                new MenuItem("Seafood Risotto", "Creamy rice with seafood", 16.50),
                new MenuItem("Bruschetta", "Tomato on toast", 7.00),
                new MenuItem("Sarde in Saor", "Sweet and sour sardines", 12.00),
                new MenuItem("Risotto al Nero di Seppia", "Black squid ink risotto", 17.00),
                new MenuItem("Bigoli in Salsa", "Pasta with anchovy sauce", 13.00),
                new MenuItem("Fegato alla Veneziana", "Venetian liver", 15.50),
                new MenuItem("Baccalà Mantecato", "Creamed cod", 14.00),
                new MenuItem("Moleche", "Soft shell crab", 22.00),
                new MenuItem("Risi e Bisi", "Rice and peas", 11.50),
                new MenuItem("Pasta e Fagioli", "Pasta and beans", 10.50),
                new MenuItem("Polenta", "Cornmeal dish", 9.00),
                new MenuItem("Fritto Misto", "Mixed fried seafood", 19.50),
                new MenuItem("Calamari Fritti", "Fried squid", 13.50),
                new MenuItem("Scampi", "Langoustines", 24.00),
                new MenuItem("Carpaccio", "Thin sliced raw beef", 15.00),
                new MenuItem("Fritole", "Venetian fritters", 6.00),
                new MenuItem("Tiramisu", "Coffee dessert", 7.50),
                new MenuItem("Zaeti", "Cornmeal cookies", 5.00),
                new MenuItem("Prosecco", "Sparkling wine", 8.00),
                new MenuItem("Spritz", "Venetian aperitif", 7.50)
            ));
            Restaurant r31 = new Restaurant(null, "Tuscany Grill", "Italian", "Italy", "€", 4.8, "https://picsum.photos/seed/tuscany/400/250", List.of(
                new MenuItem("Bistecca Fiorentina", "T-bone steak", 28.00),
                new MenuItem("Pappardelle", "Wide pasta with ragu", 13.50),
                new MenuItem("Ribollita", "Tuscan bread soup", 9.50),
                new MenuItem("Pappa al Pomodoro", "Tomato bread soup", 9.00),
                new MenuItem("Panzanella", "Bread salad", 8.50),
                new MenuItem("Crostini Toscani", "Chicken liver toast", 8.00),
                new MenuItem("Pici Cacio e Pepe", "Thick pasta", 12.00),
                new MenuItem("Cinghiale", "Wild boar stew", 19.50),
                new MenuItem("Peposo", "Peppery beef stew", 17.00),
                new MenuItem("Lampredotto", "Tripe sandwich", 7.50),
                new MenuItem("Tagliata", "Sliced beef", 22.00),
                new MenuItem("Fagioli all'Uccelletto", "Beans in tomato sauce", 8.50),
                new MenuItem("Trippa alla Fiorentina", "Florence style tripe", 14.00),
                new MenuItem("Schiacciata", "Tuscan flatbread", 5.00),
                new MenuItem("Pecorino Cheese", "Sheep cheese", 9.50),
                new MenuItem("Salumi Toscani", "Tuscan cured meats", 16.00),
                new MenuItem("Cantucci", "Almond biscotti", 5.50),
                new MenuItem("Vin Santo", "Dessert wine", 6.50),
                new MenuItem("Chianti Wine", "Red Tuscan wine", 9.00),
                new MenuItem("Caffe Latte", "Milk coffee", 3.00)
            ));
            Restaurant r32 = new Restaurant(null, "Naples Pizza Co", "Italian", "Italy", "€", 4.6, "https://picsum.photos/seed/naples/400/250", List.of(
                new MenuItem("Neapolitan Pizza", "Wood-fired classic", 11.00),
                new MenuItem("Calzone", "Folded pizza", 10.50),
                new MenuItem("Pizza Marinara", "Tomato, garlic, oregano", 9.50),
                new MenuItem("Pizza Diavola", "Spicy salami", 12.00),
                new MenuItem("Pizza Quattro Stagioni", "Four seasons", 13.50),
                new MenuItem("Pizza Capricciosa", "Mixed toppings", 13.00),
                new MenuItem("Friarielli e Salsiccia", "Greens and sausage", 11.50),
                new MenuItem("Pasta alla Genovese", "Onion beef sauce", 12.50),
                new MenuItem("Spaghetti alle Vongole", "Clam pasta", 14.50),
                new MenuItem("Ragù Napoletano", "Slow-cooked meat sauce", 13.50),
                new MenuItem("Parmigiana di Melanzane", "Eggplant parmesan", 11.00),
                new MenuItem("Impepata di Cozze", "Peppered mussels", 13.00),
                new MenuItem("Polpo alla Luciana", "Octopus in tomato", 17.00),
                new MenuItem("Frittura di Paranza", "Mixed fried fish", 16.50),
                new MenuItem("Mozzarella di Bufala", "Buffalo mozzarella", 10.00),
                new MenuItem("Sfogliatella", "Pastry with ricotta", 4.50),
                new MenuItem("Babà", "Rum cake", 5.00),
                new MenuItem("Pastiera", "Easter wheat pie", 6.00),
                new MenuItem("Limoncello", "Lemon liqueur", 5.50),
                new MenuItem("Caffè Napoletano", "Strong espresso", 2.00)
            ));
            Restaurant r33 = new Restaurant(null, "Milan Cafe", "Italian", "Italy", "€", 4.5, "https://picsum.photos/seed/milan/400/250", List.of(
                new MenuItem("Risotto Milanese", "Saffron risotto", 13.00),
                new MenuItem("Osso Buco", "Braised veal shanks", 20.00),
                new MenuItem("Cotoletta alla Milanese", "Breaded veal cutlet", 18.50),
                new MenuItem("Cassoeula", "Pork and cabbage stew", 16.00),
                new MenuItem("Minestrone alla Milanese", "Vegetable soup", 8.50),
                new MenuItem("Mondeghili", "Meatballs", 11.00),
                new MenuItem("Risotto al Salto", "Fried risotto cake", 12.50),
                new MenuItem("Nervetti", "Veal cartilage salad", 9.50),
                new MenuItem("Busecca", "Tripe soup", 10.50),
                new MenuItem("Risotto con le Rane", "Frog risotto", 17.00),
                new MenuItem("Polenta e Brasato", "Polenta with braised beef", 19.00),
                new MenuItem("Pizzoccheri", "Buckwheat pasta", 14.00),
                new MenuItem("Michetta", "Milan bread roll", 2.50),
                new MenuItem("Gorgonzola", "Blue cheese", 8.00),
                new MenuItem("Salame Milano", "Milan salami", 10.00),
                new MenuItem("Panettone", "Christmas sweet bread", 12.00),
                new MenuItem("Colomba", "Easter dove cake", 11.00),
                new MenuItem("Amaretti", "Almond cookies", 5.50),
                new MenuItem("Macchiato", "Espresso with milk", 2.50),
                new MenuItem("Aperol Spritz", "Italian aperitif", 7.00)
            ));
            Restaurant r34 = new Restaurant(null, "Sicily Kitchen", "Italian", "Italy", "€", 4.7, "https://picsum.photos/seed/sicily/400/250", List.of(
                new MenuItem("Arancini", "Fried rice balls", 7.00),
                new MenuItem("Pasta alla Norma", "Eggplant pasta", 11.50),
                new MenuItem("Pasta con le Sarde", "Pasta with sardines", 13.00),
                new MenuItem("Caponata", "Sweet and sour eggplant", 9.50),
                new MenuItem("Involtini di Pesce Spada", "Swordfish rolls", 18.00),
                new MenuItem("Cuscus di Pesce", "Fish couscous", 16.50),
                new MenuItem("Pasta alla Trapanese", "Almond pesto pasta", 12.00),
                new MenuItem("Sarde a Beccafico", "Stuffed sardines", 14.50),
                new MenuItem("Stigghiola", "Grilled intestines", 10.50),
                new MenuItem("Pani ca' Meusa", "Spleen sandwich", 6.50),
                new MenuItem("Panelle", "Chickpea fritters", 5.50),
                new MenuItem("Insalata di Mare", "Seafood salad", 15.00),
                new MenuItem("Pesce Stocco", "Stockfish stew", 16.00),
                new MenuItem("Melanzane Ripiene", "Stuffed eggplant", 11.00),
                new MenuItem("Ricotta Salata", "Salted ricotta cheese", 8.00),
                new MenuItem("Cannoli", "Sweet ricotta pastry", 6.50),
                new MenuItem("Cassata", "Sicilian cake", 7.50),
                new MenuItem("Granita", "Shaved ice dessert", 5.00),
                new MenuItem("Nero d'Avola", "Sicilian red wine", 8.50),
                new MenuItem("Caffè Freddo", "Iced coffee", 3.50)
            ));
            Restaurant r35 = new Restaurant(null, "Genoa Harbor", "Italian", "Italy", "€", 4.6, "https://picsum.photos/seed/genoa/400/250", List.of(
                new MenuItem("Pesto Pasta", "Basil pesto linguine", 11.50),
                new MenuItem("Focaccia", "Olive oil flatbread", 4.50),
                new MenuItem("Trofie al Pesto", "Twisted pasta with pesto", 12.50),
                new MenuItem("Focaccia di Recco", "Cheese focaccia", 9.00),
                new MenuItem("Farinata", "Chickpea flatbread", 6.50),
                new MenuItem("Cappon Magro", "Layered fish salad", 22.00),
                new MenuItem("Buridda", "Fish stew", 18.00),
                new MenuItem("Cima alla Genovese", "Stuffed veal", 16.50),
                new MenuItem("Pandolce", "Sweet bread", 8.00),
                new MenuItem("Torta Pasqualina", "Easter vegetable pie", 10.50),
                new MenuItem("Minestrone alla Genovese", "Vegetable soup with pesto", 9.50),
                new MenuItem("Pansoti", "Herb-filled pasta", 13.50),
                new MenuItem("Ravioli di Magro", "Vegetarian ravioli", 12.50),
                new MenuItem("Acciughe Ripiene", "Stuffed anchovies", 11.00),
                new MenuItem("Stoccafisso", "Stockfish with potatoes", 17.00),
                new MenuItem("Mesciua", "Bean and grain soup", 8.50),
                new MenuItem("Baci di Dama", "Hazelnut cookies", 6.00),
                new MenuItem("Amaretti", "Almond macaroons", 5.50),
                new MenuItem("Vermentino", "Ligurian white wine", 8.00),
                new MenuItem("Caffè Corretto", "Espresso with liquor", 4.00)
            ));
            Restaurant r36 = new Restaurant(null, "Bologna Tradition", "Italian", "Italy", "€", 4.8, "https://picsum.photos/seed/bologna/400/250", List.of(
                new MenuItem("Tagliatelle Bolognese", "Meat sauce pasta", 12.50),
                new MenuItem("Tortellini", "Stuffed pasta", 13.50),
                new MenuItem("Lasagne Bolognese", "Layered pasta", 14.00),
                new MenuItem("Tortelloni", "Large stuffed pasta", 13.00),
                new MenuItem("Gramigna con Salsiccia", "Curly pasta with sausage", 12.00),
                new MenuItem("Passatelli", "Bread pasta in broth", 10.50),
                new MenuItem("Mortadella", "Bologna sausage", 9.00),
                new MenuItem("Crescentine", "Fried dough", 7.50),
                new MenuItem("Tigelle", "Small flatbreads", 8.00),
                new MenuItem("Cotoletta alla Bolognese", "Breaded cutlet with ham", 16.50),
                new MenuItem("Zuppa Imperiale", "Imperial soup", 9.50),
                new MenuItem("Certosino", "Spiced fruit cake", 7.00),
                new MenuItem("Ravioli Bolognesi", "Meat-filled ravioli", 13.50),
                new MenuItem("Tagliatelle Verdi", "Spinach pasta", 12.00),
                new MenuItem("Bollito Misto", "Mixed boiled meats", 19.00),
                new MenuItem("Parmigiano Reggiano", "Parmesan cheese", 10.00),
                new MenuItem("Aceto Balsamico", "Balsamic vinegar tasting", 12.00),
                new MenuItem("Zuppa Inglese", "Trifle dessert", 6.50),
                new MenuItem("Lambrusco", "Sparkling red wine", 7.50),
                new MenuItem("Nocino", "Walnut liqueur", 5.50)
            ));
            
            repo.saveAll(List.of(r1,r2,r3,r4,r5,r6,r7,r8,r9,r10,r11,r12,r13,r14,r15,r16,r17,r18,r19,r20,r21,r22,r23,r24,r25,r26,r27,r28,r29,r30,r31,r32,r33,r34,r35,r36));
        };
    }
}
